"""Add best practice events models

Revision ID: 03ffaf36bfcf
Revises: cec1ae63858b
Create Date: 2025-10-02 00:33:44.254201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ffaf36bfcf'
down_revision = 'cec1ae63858b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('best_practice_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titolo', sa.String(length=200), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=False),
    sa.Column('data_evento', sa.DateTime(), nullable=False),
    sa.Column('durata_minuti', sa.Integer(), nullable=True),
    sa.Column('location_fisica', sa.String(length=300), nullable=True),
    sa.Column('link_webinar', sa.String(length=500), nullable=True),
    sa.Column('speakers', sa.JSON(), nullable=True),
    sa.Column('visibile_sponsor', sa.Boolean(), nullable=True),
    sa.Column('visibile_club', sa.Boolean(), nullable=True),
    sa.Column('solo_premium', sa.Boolean(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('agenda_url', sa.String(length=500), nullable=True),
    sa.Column('materiali_urls', sa.JSON(), nullable=True),
    sa.Column('max_partecipanti', sa.Integer(), nullable=True),
    sa.Column('richiedi_conferma', sa.Boolean(), nullable=True),
    sa.Column('abilita_qna', sa.Boolean(), nullable=True),
    sa.Column('registra_evento', sa.Boolean(), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('pubblicato', sa.Boolean(), nullable=True),
    sa.Column('note_partecipanti', sa.Text(), nullable=True),
    sa.Column('creato_da_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creato_da_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=True),
    sa.Column('domanda', sa.Text(), nullable=False),
    sa.Column('risposta', sa.Text(), nullable=True),
    sa.Column('risposto_da', sa.String(length=200), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('upvoted_by', sa.JSON(), nullable=True),
    sa.Column('moderato', sa.Boolean(), nullable=True),
    sa.Column('risposto', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('risposto_il', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['best_practice_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=True),
    sa.Column('user_email', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('ha_partecipato', sa.Boolean(), nullable=True),
    sa.Column('minuti_partecipazione', sa.Integer(), nullable=True),
    sa.Column('domande_qna', sa.JSON(), nullable=True),
    sa.Column('materiali_scaricati', sa.JSON(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback_testo', sa.Text(), nullable=True),
    sa.Column('registrato_il', sa.DateTime(), nullable=True),
    sa.Column('confermato_il', sa.DateTime(), nullable=True),
    sa.Column('cancellato_il', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['best_practice_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_type', 'user_id', name='unique_event_registration')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_registrations')
    op.drop_table('event_questions')
    op.drop_table('best_practice_events')
    # ### end Alembic commands ###
