"""add event invitations and registration form models

Revision ID: 0ccebed62631
Revises: efc794de8d43
Create Date: 2025-10-10 18:11:14.669642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ccebed62631'
down_revision = 'efc794de8d43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_form_schema', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('richiede_iscrizione', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('max_iscrizioni', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('max_iscrizioni')
        batch_op.drop_column('richiede_iscrizione')
        batch_op.drop_column('registration_form_schema')

    # ### end Alembic commands ###
