"""add_creato_da_fields_to_checklist

Revision ID: 0d65a1a018f3
Revises: d6d3749eb00f
Create Date: 2025-10-16 17:04:47.577476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d65a1a018f3'
down_revision = 'd6d3749eb00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creato_da', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('creato_da_user', sa.String(length=100), nullable=True))

    with op.batch_alter_table('event_registration_forms', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('unique_event_sponsor_registration', ['event_id', 'sponsor_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_registration_forms', schema=None) as batch_op:
        batch_op.drop_constraint('unique_event_sponsor_registration', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.drop_column('creato_da_user')
        batch_op.drop_column('creato_da')

    # ### end Alembic commands ###
