"""add admin calendar events availability demo bookings

Revision ID: 27db02646058
Revises: 8c375d636c8c
Create Date: 2026-02-12 14:12:29.902856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27db02646058'
down_revision = '8c375d636c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_refresh_token', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('google_refresh_token')

    # ### end Alembic commands ###
