"""Add club activation token fields

Revision ID: 3e14abfad6d5
Revises: 778595cec055
Create Date: 2026-02-03 18:57:35.735392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e14abfad6d5'
down_revision = '778595cec055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activation_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('activation_token_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_activated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('activated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_unique_constraint('uq_clubs_activation_token', ['activation_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_constraint('uq_clubs_activation_token', type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('activated_at')
        batch_op.drop_column('is_activated')
        batch_op.drop_column('activation_token_expires')
        batch_op.drop_column('activation_token')

    # ### end Alembic commands ###
