"""Add HeadOfTerms, Asset, Checklist, Document, Media, Notification models

Revision ID: 3f94803c41d6
Revises: 
Create Date: 2025-10-01 19:40:09.042382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f94803c41d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipologia', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('codice_fiscale', sa.String(length=16), nullable=True),
    sa.Column('partita_iva', sa.String(length=11), nullable=True),
    sa.Column('numero_affiliazione', sa.String(length=50), nullable=True),
    sa.Column('indirizzo_sede_legale', sa.String(length=300), nullable=True),
    sa.Column('indirizzo_sede_operativa', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('sito_web', sa.String(length=200), nullable=True),
    sa.Column('referente_nome', sa.String(length=100), nullable=True),
    sa.Column('referente_cognome', sa.String(length=100), nullable=True),
    sa.Column('referente_ruolo', sa.String(length=100), nullable=True),
    sa.Column('referente_contatto', sa.String(length=100), nullable=True),
    sa.Column('numero_tesserati', sa.Integer(), nullable=True),
    sa.Column('categoria_campionato', sa.String(length=200), nullable=True),
    sa.Column('facebook', sa.String(length=200), nullable=True),
    sa.Column('instagram', sa.String(length=200), nullable=True),
    sa.Column('tiktok', sa.String(length=200), nullable=True),
    sa.Column('pubblico_medio', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nome_abbonamento', sa.String(length=100), nullable=True),
    sa.Column('costo_abbonamento', sa.Float(), nullable=True),
    sa.Column('data_scadenza_licenza', sa.DateTime(), nullable=True),
    sa.Column('account_attivo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('titolo', sa.String(length=200), nullable=False),
    sa.Column('messaggio', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('letta', sa.Boolean(), nullable=True),
    sa.Column('letta_il', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fatture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('numero_fattura', sa.String(length=50), nullable=False),
    sa.Column('data_fattura', sa.DateTime(), nullable=False),
    sa.Column('importo', sa.Float(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamenti',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('importo', sa.Float(), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('metodo_pagamento', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('ragione_sociale', sa.String(length=200), nullable=False),
    sa.Column('partita_iva', sa.String(length=11), nullable=True),
    sa.Column('codice_fiscale', sa.String(length=16), nullable=True),
    sa.Column('settore_merceologico', sa.String(length=200), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('indirizzo_sede', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('sito_web', sa.String(length=200), nullable=True),
    sa.Column('referente_nome', sa.String(length=100), nullable=True),
    sa.Column('referente_cognome', sa.String(length=100), nullable=True),
    sa.Column('referente_ruolo', sa.String(length=100), nullable=True),
    sa.Column('referente_contatto', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('account_attivo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('caricato_da', sa.String(length=50), nullable=False),
    sa.Column('caricato_da_user', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('head_of_terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('nome_contratto', sa.String(length=200), nullable=False),
    sa.Column('compenso', sa.Float(), nullable=False),
    sa.Column('data_inizio', sa.DateTime(), nullable=False),
    sa.Column('data_fine', sa.DateTime(), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('file_contratto_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('caricato_da', sa.String(length=50), nullable=False),
    sa.Column('caricato_da_user', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('head_of_terms_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('quantita_totale', sa.Integer(), nullable=True),
    sa.Column('quantita_utilizzata', sa.Integer(), nullable=True),
    sa.Column('valore', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['head_of_terms_id'], ['head_of_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('head_of_terms_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('titolo', sa.String(length=200), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('priorita', sa.String(length=50), nullable=True),
    sa.Column('assegnato_a', sa.String(length=50), nullable=False),
    sa.Column('completato', sa.Boolean(), nullable=True),
    sa.Column('completato_da', sa.String(length=100), nullable=True),
    sa.Column('completato_il', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['head_of_terms_id'], ['head_of_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklists')
    op.drop_table('assets')
    op.drop_table('media')
    op.drop_table('head_of_terms')
    op.drop_table('documents')
    op.drop_table('sponsors')
    op.drop_table('pagamenti')
    op.drop_table('fatture')
    op.drop_table('notifications')
    op.drop_table('clubs')
    op.drop_table('admins')
    # ### end Alembic commands ###
