"""Add geolocation fields to MarketplaceOpportunity

Revision ID: 6bec22551e14
Revises: 40bd2278d743
Create Date: 2025-12-09 17:18:59.458028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bec22551e14'
down_revision = '40bd2278d743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location_province', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location_region', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('location_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('location_lng', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marketplace_opportunities', schema=None) as batch_op:
        batch_op.drop_column('location_lng')
        batch_op.drop_column('location_lat')
        batch_op.drop_column('location_country')
        batch_op.drop_column('location_region')
        batch_op.drop_column('location_province')
        batch_op.drop_column('location_city')

    # ### end Alembic commands ###
