"""add_club_brand_settings

Revision ID: 7a8d75018fcb
Revises: 511adc20edfe
Create Date: 2026-01-29 17:37:28.271062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8d75018fcb'
down_revision = '511adc20edfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_colore_primario', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('brand_colore_secondario', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('brand_colore_accento', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('brand_font', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('brand_stile_proposta', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('brand_logo_chiaro', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('brand_sfondo_header', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('brand_footer_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('brand_footer_text')
        batch_op.drop_column('brand_sfondo_header')
        batch_op.drop_column('brand_logo_chiaro')
        batch_op.drop_column('brand_stile_proposta')
        batch_op.drop_column('brand_font')
        batch_op.drop_column('brand_colore_accento')
        batch_op.drop_column('brand_colore_secondario')
        batch_op.drop_column('brand_colore_primario')

    # ### end Alembic commands ###
