"""make contract_id and sponsor_id nullable in projects

Revision ID: 90e70cfa855b
Revises: f4d9b8c73f21
Create Date: 2025-10-02 13:31:48.808271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e70cfa855b'
down_revision = 'f4d9b8c73f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('contract_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sponsor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.alter_column('sponsor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('contract_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
