"""add quantita_utilizzata to activation

Revision ID: a55e36459a93
Revises: social_features_002
Create Date: 2025-10-23 00:23:25.369307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a55e36459a93'
down_revision = 'social_features_002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantita_utilizzata', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activations', schema=None) as batch_op:
        batch_op.drop_column('quantita_utilizzata')

    # ### end Alembic commands ###
