"""Add meet_link to AdminCalendarEvent and DemoBooking

Revision ID: af2638d9c9f1
Revises: 27db02646058
Create Date: 2026-02-14 11:55:33.218175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af2638d9c9f1'
down_revision = '27db02646058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meet_link', sa.String(length=500), nullable=True))

    with op.batch_alter_table('demo_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meet_link', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demo_bookings', schema=None) as batch_op:
        batch_op.drop_column('meet_link')

    with op.batch_alter_table('admin_calendar_events', schema=None) as batch_op:
        batch_op.drop_column('meet_link')

    # ### end Alembic commands ###
