"""add_sponsor_from_lead_fields

Revision ID: c9bf35930b6f
Revises: 7a8d75018fcb
Create Date: 2026-01-29 18:45:05.458603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9bf35930b6f'
down_revision = '7a8d75018fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_lead_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_conversione_lead', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_sponsors_from_lead_id', 'leads', ['from_lead_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsors', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sponsors_from_lead_id', type_='foreignkey')
        batch_op.drop_column('data_conversione_lead')
        batch_op.drop_column('from_lead_id')

    # ### end Alembic commands ###
