"""Add press area models

Revision ID: cec1ae63858b
Revises: 3f94803c41d6
Create Date: 2025-10-02 00:19:07.362933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec1ae63858b'
down_revision = '3f94803c41d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('press_publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titolo', sa.String(length=200), nullable=False),
    sa.Column('sottotitolo', sa.String(length=300), nullable=True),
    sa.Column('testo', sa.Text(), nullable=False),
    sa.Column('data_pubblicazione', sa.DateTime(), nullable=False),
    sa.Column('fonte_testata', sa.String(length=200), nullable=True),
    sa.Column('link_esterno', sa.String(length=500), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('media_urls', sa.JSON(), nullable=True),
    sa.Column('documento_pdf_url', sa.String(length=500), nullable=True),
    sa.Column('visibile_tutti_sponsor', sa.Boolean(), nullable=True),
    sa.Column('visibile_solo_attivi', sa.Boolean(), nullable=True),
    sa.Column('sponsor_ids', sa.JSON(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('tagged_sponsor_ids', sa.JSON(), nullable=True),
    sa.Column('visualizzazioni_count', sa.Integer(), nullable=True),
    sa.Column('creato_da_user_id', sa.Integer(), nullable=True),
    sa.Column('creato_da_nome', sa.String(length=200), nullable=True),
    sa.Column('pubblicato', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['head_of_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('press_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.Column('testo', sa.Text(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['press_comments.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['press_publications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('press_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('tipo_reazione', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['press_publications.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_id', 'sponsor_id', name='unique_reaction_per_sponsor')
    )
    op.create_table('press_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('visualizzato_il', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['press_publications.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['sponsors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('press_views')
    op.drop_table('press_reactions')
    op.drop_table('press_comments')
    op.drop_table('press_publications')
    # ### end Alembic commands ###
