"""Add archive fields to InventoryAsset

Revision ID: d0ae9edec04c
Revises: 6bec22551e14
Create Date: 2026-01-27 17:26:56.676358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ae9edec04c'
down_revision = '6bec22551e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archiviato', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_archiviazione', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('motivo_archiviazione', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_assets', schema=None) as batch_op:
        batch_op.drop_column('motivo_archiviazione')
        batch_op.drop_column('data_archiviazione')
        batch_op.drop_column('archiviato')

    # ### end Alembic commands ###
