"""add scadenza field to checklist

Revision ID: efc794de8d43
Revises: 90e70cfa855b
Create Date: 2025-10-10 16:18:30.691655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc794de8d43'
down_revision = '90e70cfa855b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scadenza', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.drop_column('scadenza')

    # ### end Alembic commands ###
